log_prefix := "[JUST][format_md][reduce_header_levels]"

run md_src_dpath:
    #!/usr/bin/env bash
    set -euo pipefail
    echo >&2 "{{log_prefix}}"

    # Walk through all MD files in the source directory
    find "{{md_src_dpath}}" -type f -name "*.md" | while read -r md_file_path; do
        # Find the first header and count the number of # symbols
        first_header=$(grep --color=never -m 1 "^#" "$md_file_path" | sed -E 's/(#+).*/\1/')
        first_header_length=${#first_header}  # Get the length of the header (i.e., number of # symbols)

        if [[ $first_header_length -gt 1 ]]; then
            # Reduce the number of # symbols in all headers by the first header length minus one
            sed -i -E "s/^#{$first_header_length}/#/" "$md_file_path"
        fi
    done
