log_prefix := "[JUST][format_md][convert_headers_title_case]"

run md_src_dpath:
    #!/usr/bin/env bash
    set -euo pipefail
    echo >&2 "{{log_prefix}}"

    # Walk through all MD files in the source directory
    find "{{md_src_dpath}}" -type f -name "*.md" | while read -r md_file_path; do
        sed -E '/^#+ /{s/(#+)\s*(.*)/\1 \L\2/g; s/(#+\s*)([a-z])/\1\u\2/g; s/\s([a-z])/ \u\1/g}' "$md_file_path" > .tmp
        mv .tmp "$md_file_path"
    done
