log_prefix := "[JUST][extract_html_sections][common]"

# Generate markdown files for all matches of an xpath (via html)
extract_section destination_path xpath src_html_fpath skip_delete="true":
    #!/usr/bin/env bash
    set -euo pipefail
    echo >&2 "{{log_prefix}} --- Generating {{destination_path}} --- "

    if [ "{{skip_delete}}" == "true" ]; then
        rm -rf "{{destination_path}}"
    else
        echo >&2 "Skipping delete on dir '{{destination_path}}'"
    fi

    python3 ./query.py "{{xpath}}" "{{src_html_fpath}}" "{{destination_path}}"
    # TODO - move this
    #html_folder_to_md "{{destination_path}}"
