log_prefix := "[JUST][yaml_statblock_to_md]"

run yaml_src_dpath md_dest_dpath:
    #!/usr/bin/env bash
    set -euo pipefail
    echo >&2 "{{log_prefix}} --- Converting yaml statblock to markdown --- "
    echo >&2 "{{log_prefix}} YAML source: {{yaml_src_dpath}}"
    echo >&2 "{{log_prefix}} MD dest: {{md_dest_dpath}}"

    mkdir -p "{{md_dest_dpath}}"

    # Walk through all MD files in the source directory
    find "{{yaml_src_dpath}}" -type f -name "*.yaml" | while read -r yaml_file_path; do
        md_filename="$(basename "$yaml_file_path" | sed 's/yaml/md/')"
        python3 yaml_statblock_to_md.py "$yaml_file_path" "{{md_dest_dpath}}/${md_filename}"
    done
