log_prefix := "[JUST][format_statblock_md]"

run md_src_dpath:
    #!/usr/bin/env bash
    set -euo pipefail
    echo >&2 "{{log_prefix}} --- Formatting statblock markdown --- "
    echo >&2 "{{log_prefix}} MD source: {{md_src_dpath}}"

    # Walk through all MD files in the source directory
    find "{{md_src_dpath}}" -type f -name "*.md" | while read -r md_file_path; do
        python3 format_statblock.py "$md_file_path"
    done
