log_prefix := "[JUST][extract_statblocks]"

# TODO - this should be split up
run md_src_fpath statblock_dest_dpath:
    #!/usr/bin/env bash
    set -euo pipefail
    echo >&2 "{{log_prefix}} --- Extracting Statblocks --- "

    md_dpath="{{statblock_dest_dpath}}/md"
    md_dse_dpath="{{statblock_dest_dpath}}/md-dse"
    yaml_dpath="{{statblock_dest_dpath}}/yaml"

    echo >&2 "{{log_prefix}} MD dest: $md_dpath"
    echo >&2 "{{log_prefix}} MD DSE dest: $md_dse_dpath"
    echo >&2 "{{log_prefix}} YAML dest: $yaml_dpath"

    python3 extract_statblocks.py "{{md_src_fpath}}" "$md_dpath" "$md_dse_dpath" "$yaml_dpath"
