log_prefix := "[JUST][format_md]"

run md_src_dpath md_dest_dpath:
    #!/usr/bin/env bash
    set -euo pipefail
    echo >&2 "{{log_prefix}} --- Transforming markdown --- "
    echo >&2 "{{log_prefix}} MD unformatted source: {{md_src_dpath}}"
    echo >&2 "{{log_prefix}} MD Formatted dest: {{md_dest_dpath}}"

    # Copy the MD files to destination
    mkdir -p "{{md_dest_dpath}}"
    cp -R "{{md_src_dpath}}"/* "{{md_dest_dpath}}"

    # All of these transform the markdown files in-place
    just -f convert_headers_title_case/justfile run "{{md_dest_dpath}}"
    just -f reduce_header_levels/justfile run "{{md_dest_dpath}}"
    just -f frontmatter/justfile run "{{md_dest_dpath}}"
    just -f convert_ktdt_tables/justfile run "{{md_dest_dpath}}"
