#!/usr/bin/env just --justfile

log_prefix := "[JUST][extract_html_sections]"

run rules_html_fpath rules_html_sections_dpath:
    just _extract_classes "{{rules_html_fpath}}" "{{rules_html_sections_dpath}}"
    just _extract_abilities "{{rules_html_fpath}}" "{{rules_html_sections_dpath}}"
    just _extract_movement "{{rules_html_fpath}}" "{{rules_html_sections_dpath}}"
    just _extract_kits "{{rules_html_fpath}}" "{{rules_html_sections_dpath}}"
    just _extract_ancestries "{{rules_html_fpath}}" "{{rules_html_sections_dpath}}"
    just _extract_careers "{{rules_html_fpath}}" "{{rules_html_sections_dpath}}"
    just _extract_cultures "{{rules_html_fpath}}" "{{rules_html_sections_dpath}}"
    just _extract_complications "{{rules_html_fpath}}" "{{rules_html_sections_dpath}}"
    just _extract_conditions "{{rules_html_fpath}}" "{{rules_html_sections_dpath}}"
    just _extract_skills "{{rules_html_fpath}}" "{{rules_html_sections_dpath}}"
    just _extract_negotiation "{{rules_html_fpath}}" "{{rules_html_sections_dpath}}"
    just _extract_perks "{{rules_html_fpath}}" "{{rules_html_sections_dpath}}"
    just _extract_titles "{{rules_html_fpath}}" "{{rules_html_sections_dpath}}"

_extract_classes rules_html_fpath rules_html_sections_dpath:
    #!/usr/bin/env bash
    set -euo pipefail

    classes_path="{{rules_html_sections_dpath}}/Classes Single Page"
    # delete dir on first one, keep on others
    just -f "../common/justfile" extract_section "$classes_path" "//section[@id='censor']" "{{rules_html_fpath}}"
    just -f "../common/justfile" extract_section "$classes_path" "//section[@id='conduit']" "{{rules_html_fpath}}"
    just -f "../common/justfile" extract_section "$classes_path" "//section[@id='elementalist']" "{{rules_html_fpath}}" "skip_delete"
    just -f "../common/justfile" extract_section "$classes_path" "//section[@id='fury']" "{{rules_html_fpath}}" "skip_delete"
    just -f "../common/justfile" extract_section "$classes_path" "//section[@id='null']" "{{rules_html_fpath}}" "skip_delete"
    just -f "../common/justfile" extract_section "$classes_path" "//section[@id='shadow']" "{{rules_html_fpath}}" "skip_delete"
    just -f "../common/justfile" extract_section "$classes_path" "//section[@id='tactician']" "{{rules_html_fpath}}" "skip_delete"
    just -f "../common/justfile" extract_section "$classes_path" "//section[@id='talent']" "{{rules_html_fpath}}" "skip_delete"
    just -f "../common/justfile" extract_section "$classes_path" "//section[@id='troubadour']" "{{rules_html_fpath}}" "skip_delete"

_extract_abilities rules_html_fpath rules_html_sections_dpath:
    #!/usr/bin/env bash
    set -euo pipefail

    abilities_path="{{rules_html_sections_dpath}}/Abilities"

    # Common Maneuvers, actions, and move actions
    just -f "../common/justfile" extract_section "$abilities_path/Common Maneuvers" "//section[@id='combat']//section[@id='maneuvers']//section[@class='level3']" "{{rules_html_fpath}}"
    just -f "../common/justfile" extract_section "$abilities_path/Common Actions" "//section[@id='combat']//section[@id='actions']//section[@class='level3']" "{{rules_html_fpath}}"
    just -f "../common/justfile" extract_section "$abilities_path/Common Move Actions" "//section[@id='combat']//section[@id='move-actions']//section[@class='level3']" "{{rules_html_fpath}}"

_extract_movement rules_html_fpath rules_html_sections_dpath:
    #!/usr/bin/env bash
    set -euo pipefail

    movement_path="{{rules_html_sections_dpath}}/Movement"

    xpath="//section[@id='combat']//section[@id='movement']//section[@class='level3']"
    just -f "../common/justfile" extract_section "$movement_path" "$xpath" "{{rules_html_fpath}}"
    xpath="//section[@id='combat']//section[@id='movement-types']//section[@class='level4']"
    just -f "../common/justfile" extract_section "$movement_path" "$xpath" "{{rules_html_fpath}}" "skip_delete"

    rm "${movement_path}/CanT Exceed Speed.html"
    rm "${movement_path}/Movement Types.html"

_extract_kits rules_html_fpath rules_html_sections_dpath:
    #!/usr/bin/env bash
    set -euo pipefail

    martial_path="{{rules_html_sections_dpath}}/Kits"
    xpath="//section[@id='kits']//section[@id='kits-a-to-z']//section[@class='level3']"
    just -f "../common/justfile" extract_section "$martial_path" "$xpath" "{{rules_html_fpath}}"

_extract_ancestries rules_html_fpath rules_html_sections_dpath:
    #!/usr/bin/env bash
    set -euo pipefail
    ancestries_path="{{rules_html_sections_dpath}}/Ancestries"
    xpath="//section[@id='ancestries']//section[@class='level2']"
    just -f "../common/justfile" extract_section "$ancestries_path" "$xpath" "{{rules_html_fpath}}"

    # removes any extra sections
    rm "${ancestries_path}/Starting Size And Speed.html"
    rm "${ancestries_path}/On The Origin Of Species.html"

_extract_careers rules_html_fpath rules_html_sections_dpath:
    #!/usr/bin/env bash
    set -euo pipefail
    careers_path="{{rules_html_sections_dpath}}/Careers"
    xpath="//section[@id='career-1']//section[@class='level2']"
    just -f "../common/justfile" extract_section "$careers_path" "$xpath" "{{rules_html_fpath}}"

    # removes any extra sections
    rm "${careers_path}/Career Benefits.html"
    rm "${careers_path}/Career Questions.html"
    rm "${careers_path}/Inciting Incident.html"

_extract_cultures rules_html_fpath rules_html_sections_dpath:
    #!/usr/bin/env bash
    set -euo pipefail
    cultures_path="{{rules_html_sections_dpath}}/Cultures"

    xpath="//section[@id='culture-1']//section[@id='culture-benefits']//section[@id='environment']//section[@class='level4']"
    just -f "../common/justfile" extract_section "$cultures_path/Environments" "$xpath" "{{rules_html_fpath}}"

    xpath="//section[@id='culture-1']//section[@id='culture-benefits']//section[@id='organization']//section[@class='level4']"
    just -f "../common/justfile" extract_section "$cultures_path/Organizations" "$xpath" "{{rules_html_fpath}}"

    xpath="//section[@id='culture-1']//section[@id='culture-benefits']//section[@id='upbringing']//section[@class='level4']"
    just -f "../common/justfile" extract_section "$cultures_path/Upbringing" "$xpath" "{{rules_html_fpath}}"

    # removes any extra sections
    rm "${cultures_path}/Upbringing/But I Really Want Alertness.html"

_extract_complications rules_html_fpath rules_html_sections_dpath:
    #!/usr/bin/env bash
    set -euo pipefail
    complications_path="{{rules_html_sections_dpath}}/Complications"
    xpath="//section[@id='complications']//section[@id='determine-complication']//section[@class='level3']"
    just -f "../common/justfile" extract_section "$complications_path" "$xpath" "{{rules_html_fpath}}"

_extract_skills rules_html_fpath rules_html_sections_dpath:
    #!/usr/bin/env bash
    set -euo pipefail
    skills_path="{{rules_html_sections_dpath}}/Skills"
    xpath="//section[@id='tests']//section[@id='skill-groups']//section[@class='level4']"
    just -f "../common/justfile" extract_section "$skills_path" "$xpath" "{{rules_html_fpath}}"

    # removes any extra sections
    rm "${skills_path}/Are All Skills Equal?.html"
    rm "${skills_path}/For The Director: Make Your Own Skills.html"

_extract_conditions rules_html_fpath rules_html_sections_dpath:
    #!/usr/bin/env bash
    set -euo pipefail
    conditions_path="{{rules_html_sections_dpath}}/Conditions"
    xpath="//section[@id='abilities']//section[@id='conditions']//section[@class='level3']"
    just -f "../common/justfile" extract_section "$conditions_path" "$xpath" "{{rules_html_fpath}}"

_extract_negotiation rules_html_fpath rules_html_sections_dpath:
    #!/usr/bin/env bash
    set -euo pipefail

    negotiation_path="{{rules_html_sections_dpath}}/Negotiation"
    xpath="//section[@id='list-of-motivations-and-pitfalls']//section[@class='level4']"
    just -f "../common/justfile" extract_section "$negotiation_path/Motivations and Pitfalls" "$xpath" "{{rules_html_fpath}}"

_extract_perks rules_html_fpath rules_html_sections_dpath:
    #!/usr/bin/env bash
    set -euo pipefail
    perks_path="{{rules_html_sections_dpath}}/Perks"
    xpath="//section[@id='crafting-perks']//section[@class='level3']"
    just -f "../common/justfile" extract_section "${perks_path}/Crafting Perks" "$xpath" "{{rules_html_fpath}}"
    xpath="//section[@id='exploration-perks']//section[@class='level3']"
    just -f "../common/justfile" extract_section "${perks_path}/Exploration Perks" "$xpath" "{{rules_html_fpath}}"
    xpath="//section[@id='interpersonal-perks']//section[@class='level3']"
    just -f "../common/justfile" extract_section "${perks_path}/Interpersonal Perks" "$xpath" "{{rules_html_fpath}}"
    xpath="//section[@id='intrigue-perks']//section[@class='level3']"
    just -f "../common/justfile" extract_section "${perks_path}/Intrigue Perks" "$xpath" "{{rules_html_fpath}}"
    xpath="//section[@id='lore-perks']//section[@class='level3']"
    just -f "../common/justfile" extract_section "${perks_path}/Lore Perks" "$xpath" "{{rules_html_fpath}}"
    xpath="//section[@id='supernatural-perks']//section[@class='level3']"
    just -f "../common/justfile" extract_section "${perks_path}/Supernatural Perks" "$xpath" "{{rules_html_fpath}}"

_extract_titles rules_html_fpath rules_html_sections_dpath:
    #!/usr/bin/env bash
    set -euo pipefail
    titles_path="{{rules_html_sections_dpath}}/Titles"
    xpath="//section[@id='st-echelon-titles']//section[@class='level3']"
    just -f "../common/justfile" extract_section "${titles_path}" "$xpath" "{{rules_html_fpath}}"

# TODO - downtime stuff, treasures
