log_prefix := "[JUST][format_md][generate_ability_index]"

run md_src_dpath:
    #!/usr/bin/env bash
    set -euo pipefail
    echo >&2 "{{log_prefix}} --- Generating ability indexes --- "
    echo >&2 "{{log_prefix}} MD source: {{md_src_dpath}}"
    for dir in {{md_src_dpath}}/*/ ; do
        just generate_index "$dir"
    done

generate_index directory_path:
    #!/usr/bin/env bash
    set -euo pipefail

    index_name=$(basename "{{directory_path}}")
    echo >&2 "[JUST] Generating index for $index_name"

    index_path="{{directory_path}}/index.md"
    echo "# $index_name Abilities" > "$index_path"
    echo "" >> "$index_path"
    python3 ability_table.py "{{directory_path}}" -c name kind cost ability_type distance target >> "$index_path"
