log_prefix := "[JUST][format_md][mdformat]"

run md_src_dpath:
    #!/usr/bin/env bash
    set -euo pipefail
    echo >&2 "{{log_prefix}} --- Formatting Markdown --- "
    echo >&2 "{{log_prefix}} MD source: {{md_src_dpath}}"
    mdformat --version

    # convert everything to UTF-8
    find {{md_src_dpath}} -type f -name '*.md' -exec sh -c '
      for file do
        # Convert "file" in place, making a backup with a .bak extension
        echo "$file"
        iconv -f UTF-8 -t UTF-8//TRANSLIT "$file" -o "$file".temp && mv "$file".temp "$file"
      done
    ' sh {} +
    mdformat "{{md_src_dpath}}"
