# Global dirs
data_gen_root_dpath := justfile_directory() / ".."
data_root_dpath := data_gen_root_dpath / ".."

# Staging dirs
staging_dpath := data_root_dpath / "staging"

clean_and_prep:
    #!/usr/bin/env bash
    set -euo pipefail
    if [ -d "{{staging_dpath}}" ]; then
        rm -rf "{{staging_dpath}}"
    fi
    mkdir -p "{{staging_dpath}}"

gen: clean_and_prep gen_rules gen_bestiary gen_adventures gen_unified gen_unified_dse

gen_rules:
    just -f rules.justfile gen_rules

gen_bestiary:
    just -f bestiary.justfile gen_bestiary

gen_adventures:
    just -f adventures.justfile gen_adventures

gen_unified:
    just -f unified.justfile gen_unified

gen_unified_dse:
    just -f unified-dse.justfile gen_unified_dse

# deletes all the (non-hidden) files in a directory
_delete_dir_except_git dir_to_delete:
    #!/usr/bin/env bash
    set -euo pipefail
    tempdir="$(mktemp -d)"
    echo "$tempdir"
    # add a dummy file to avoid crashing in case the dir is empty
    touch "{{dir_to_delete}}/dummy.txt"
    mv "{{dir_to_delete}}"/* "${tempdir}/"
    # by default dotglob will prevent hidden files from being included in * wildcard globs
    if [ -d "${tempdir}/.git" ]; then
        mv "${tempdir}/.git" "{{dir_to_delete}}"
    fi
    rm -rf "$tempdir"
