#!/usr/bin/env just --justfile

run html_fpath html_sections_dpath:
    #!/usr/bin/env bash
    set -euo pipefail
    vp_dpath="{{html_sections_dpath}}"

    just -f "../common/justfile" extract_section "$vp_dpath" "//section[@id='ankheg-malice']" "{{html_fpath}}" "skip_delete"
    just -f "../common/justfile" extract_section "$vp_dpath" "//section[@id='basilisks-malice']" "{{html_fpath}}" "skip_delete"
    just -f "../common/justfile" extract_section "$vp_dpath" "//section[@id='bredbeddle-malice']" "{{html_fpath}}" "skip_delete"
    just -f "../common/justfile" extract_section "$vp_dpath" "//section[@id='bugbears-malice']" "{{html_fpath}}" "skip_delete"
    just -f "../common/justfile" extract_section "$vp_dpath" "//section[@id='chimera-malice']" "{{html_fpath}}" "skip_delete"
    just -f "../common/justfile" extract_section "$vp_dpath" "//section[@id='demons-malice']" "{{html_fpath}}" "skip_delete"
    just -f "../common/justfile" extract_section "$vp_dpath" "//section[@id='dwarves-malice']" "{{html_fpath}}" "skip_delete"
    just -f "../common/justfile" extract_section "$vp_dpath" "//section[@id='elves-high-malice']" "{{html_fpath}}" "skip_delete"
    just -f "../common/justfile" extract_section "$vp_dpath" "//section[@id='elves-wode-malice']" "{{html_fpath}}" "skip_delete"
    just -f "../common/justfile" extract_section "$vp_dpath" "//section[@id='fossil-cryptic-malice']" "{{html_fpath}}" "skip_delete"
    just -f "../common/justfile" extract_section "$vp_dpath" "//section[@id='gnolls-malice']" "{{html_fpath}}" "skip_delete"
    just -f "../common/justfile" extract_section "$vp_dpath" "//section[@id='goblins-malice']" "{{html_fpath}}" "skip_delete"
    just -f "../common/justfile" extract_section "$vp_dpath" "//section[@id='griffons-malice']" "{{html_fpath}}" "skip_delete"
    just -f "../common/justfile" extract_section "$vp_dpath" "//section[@id='hags-malice']" "{{html_fpath}}" "skip_delete"
